PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX av: <http://w3id.org/abecto/vocabulary#>
PREFIX dqv: <http://www.w3.org/ns/dqv#>
PREFIX oa: <http://www.w3.org/ns/oa#>

SELECT ?aspect ?missedInDataset ?missingResource (GROUP_CONCAT(?missingResourceLabel; SEPARATOR=", ") AS ?missingResourceLabelConcat) ?foundInDataset
WHERE {
  GRAPH ?graph {
    [ rdf:type  dqv:QualityAnnotation ;
      oa:hasBody 
        [ rdf:type               av:ResourceOmission ;
          av:affectedAspect      ?aspectResource ;
          av:comparedToDataset   ?foundInDataset ;
          av:comparedToResource  ?missingResource
        ] ;
      oa:hasTarget ?missedInDataset
    ] .
  }
  OPTIONAL { ?aspectResource rdfs:label ?aspectLabel .}
  OPTIONAL { 
      GRAPH ?sourceGraph {
          ?missingResource rdfs:label ?missingResourceLabel .
      }
      ?sourceGraph a av:PrimaryDataGraph ;
                   av:associatedDataset ?foundInDataset .
  }
  ?aspectResource av:keyVariableName ?aspectKeyVar .
  BIND(COALESCE(?aspectLabel, ?aspectKeyVar) AS ?aspect)
}
GROUP BY ?missedInDataset ?foundInDataset ?aspect ?missingResource
ORDER BY ?missedInDataset ?foundInDataset ?aspect ?missingResource
